services:
  - type: web
    name: slac-backend
    env: python
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 3 -b 0.0.0.0:$PORT wsgi:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: DATABASE_URL
        value: sqlite:////opt/render/project/src/uploads/slac.db
      - key: JWT_SECRET
        generateValue: true
      - key: CORS_ORIGINS
        value: "*"
      - key: UPLOAD_DIR
        value: uploads
    plan: free
    autoDeploy: true
    healthCheckPath: /api/health
    disk:
      name: uploads
      mountPath: /opt/render/project/src/uploads
      sizeGB: 1
